- name: Install Vivaldi
  apt:
    # Note: This is very likely to get out of date as it includes the version number
    # but they don't seem to have just a "stable" link.
    #
    # I started a thread to request this here:
    # https://forum.vivaldi.net/topic/92639/stable-url-for-latest-stable
    deb: https://downloads.vivaldi.com/stable/vivaldi-stable_6.4.3160.44-1_amd64.deb
  when: >
    "vivaldi-stable" not in ansible_facts.packages
  become: true
- name: remove legacy Signal signing key
  apt_key:
    url: https://updates.signal.org/desktop/apt/keys.asc
    state: absent
  become: true
- name: add Signal apt repo and signing key
  deb822_repository:
    name: signal
    types: deb
    uris: https://updates.signal.org/desktop/apt
    suites: xenial
    components:
      - main
    signed_by: https://updates.signal.org/desktop/apt/keys.asc
    state: present
  become: true
- name: Add the Spotify apt repo
  deb822_repository:
    name: spotify
    uris: http://repository.spotify.com
    suites: stable
    components: [ non-free ]
    signed_by: https://download.spotify.com/debian/pubkey_C85668DF69375001.gpg
    state: present
  become: true
- name: Install standard GUI apps
  apt:
    cache_valid_time: 600
    pkg:
      - lyx
      - signal-desktop
      - spotify-client
      # This provides Google Drive access through KDE file manager
      - kio-gdrive
  become: true
- name: See if Zotero is installed
  find:
    path: ~/Applications/
    patterns: "Zotero*.appimage"
  register: zotero_find
- name: Install Zotero
  block:
    - name: make sure Applications directory exists
      file:
        path: ~/Applications
        state: directory
    - name: Generate a Zotero appimage
      # The argument here is the version to build.
      script: zotero-appimg.sh 6.0.26
    - name: Integrate the appimage
      command: ail-cli integrate ~/Applications/Zotero.appimage
  when: zotero_find.matched == 0
