- name: install some standard packages
  apt:
     cache_valid_time: 600
     pkg:
       - ripgrep
       - fd-find
       - ranger
       - htop
       - python3-pynvim
       - xclip
       - httpie
       - tldr
       - tig
  become: true
- name: symlink fdfind to fd
  file:
    src: /usr/bin/fdfind
    dest: /usr/bin/fd
    state: link
  become: true
- name: See if neovim is installed
  stat:
     path: "{{ nvim_path }}"
  register: nvim_stat
- name: Install neovim
  block:
    - name: Download the neovim appimg
      get_url:
        url: "https://github.com/neovim/neovim/releases/download/{{ nvim_version}}/nvim.appimage"
        dest: "{{ nvim_path }}"
    - name: Make nvim executable
      file:
        path: "{{ nvim_path }}"
        state: touch
        mode: u+x
  when: not nvim_stat.stat.exists
- name: See if lakectl is installed
  stat:
    path: ~/bin/lakectl
  register: lakectl_stat
- name: Install lakefs CLI
  block:
    - name: Download lakefs tarball
      get_url:
        url: "https://github.com/treeverse/lakeFS/releases/download/v{{ lakefs_version }}/lakeFS_{{ lakefs_version }}_Linux_x86_64.tar.gz"
        dest: /tmp/lakefs.tar.gz
    - name: Extract lakefs cli
      unarchive:
        src: /tmp/lakefs.tar.gz
        include: lakectl
        dest: ~/bin
  when: not lakectl_stat.stat.exists
- name: see if k9s is installed
  stat:
    path: /usr/bin/k9s
  register: k9s_stat
- name: install k9s TUI
  apt:
    deb: https://github.com/derailed/k9s/releases/latest/download/k9s_linux_amd64.deb
  become: true
  when: not k9s_stat.stat.exists
# Kubeswitch requires a tiny bit of bash to set up the shell function. That's already in my .bashrc in yadm so no need
# to do anything else here.
- name: see if kubeswitch is installed
  stat:
    path: ~/bin/switcher
  register: kubeswitch_stat
- name: install kubeswitch
  block:
    - name: download latest version of kubeswitch
      get_url:
        url: https://github.com/danielfoehrKn/kubeswitch/releases/latest/download/switcher_linux_amd64
        dest: ~/bin/switcher
    - name: make switcher executable
      file:
        path: ~/bin/switcher
        state: touch
        mode: u+x
  when: not kubeswitch_stat.stat.exists

